// <auto-generated />
using System;
using API_Server.src.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Server.Migrations
{
    [DbContext(typeof(AppContextDB))]
    [Migration("20260124013734_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Server.src.Models.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("IdPerson")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<decimal?>("TotalMoney")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Bill__3214EC07971BEEA9");

                    b.HasIndex(new[] { "IdPerson" }, "IX_Bill_IdPerson");

                    b.HasIndex(new[] { "IdRoom" }, "IX_Bill_IdRoom");

                    b.ToTable("Bill", (string)null);
                });

            modelBuilder.Entity("API_Server.src.Models.BillDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("Electricity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid?>("IdBill")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdService")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Water")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__BillDeta__3214EC073E2B9BA4");

                    b.HasIndex(new[] { "IdBill" }, "IX_BillDetail_IdBill")
                        .IsUnique()
                        .HasFilter("([IdBill] IS NOT NULL)");

                    b.HasIndex(new[] { "IdService" }, "IX_BillDetail_IdService");

                    b.ToTable("BillDetail", (string)null);
                });

            modelBuilder.Entity("API_Server.src.Models.BookingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DesiredDurationMonths")
                        .HasColumnType("int");

                    b.Property<DateTime>("DesiredStartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdRenter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id")
                        .HasName("PK__BookingRequest__3214EC07");

                    b.HasIndex(new[] { "IdRenter" }, "IX_BookingRequest_IdRenter");

                    b.HasIndex(new[] { "IdRoom" }, "IX_BookingRequest_IdRoom");

                    b.ToTable("BookingRequest", (string)null);
                });

            modelBuilder.Entity("API_Server.src.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("IdRenter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Contract__3214EC07A2341402");

                    b.HasIndex(new[] { "IdRenter" }, "IX_Contract_IdRenter");

                    b.HasIndex(new[] { "IdRoom" }, "IX_Contract_IdRoom");

                    b.ToTable("Contract", (string)null);
                });

            modelBuilder.Entity("API_Server.src.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateIncurred")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdOwner" }, "IX_Expenses_IdOwner");

                    b.HasIndex(new[] { "IdRoom" }, "IX_Expenses_IdRoom");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("API_Server.src.Models.ListRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdOwner" }, "IX_ListRoom_IdOwner");

                    b.ToTable("ListRoom", (string)null);
                });

            modelBuilder.Entity("API_Server.src.Models.Notice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Idreport")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDReport");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Notice__3214EC071255475A");

                    b.HasIndex(new[] { "Idreport" }, "IX_Notice_IDReport")
                        .IsUnique()
                        .HasFilter("([IDReport] IS NOT NULL)");

                    b.ToTable("Notice", (string)null);
                });

            modelBuilder.Entity("API_Server.src.Models.Payment", b =>
                {
                    b.Property<Guid>("IdBill")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdBill")
                        .HasName("PK__Payment__24A2D64DE1749AF2");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("API_Server.src.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("IdDetail")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Person__3214EC07FDB564BD");

                    b.HasIndex(new[] { "IdDetail" }, "IX_Person_IdDetail")
                        .IsUnique()
                        .HasFilter("([IdDetail] IS NOT NULL)");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("API_Server.src.Models.PersonDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<byte[]>("CccdImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Gmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__PersonDe__3214EC074CE93A01");

                    b.ToTable("PersonDetail", (string)null);
                });

            modelBuilder.Entity("API_Server.src.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdReporter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Report__3214EC073003D7A2");

                    b.HasIndex(new[] { "IdReporter" }, "IX_Report_IdReporter");

                    b.HasIndex(new[] { "IdRoom" }, "IX_Report_IdRoom");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("API_Server.src.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("IdListRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Room__3214EC0720EB1BA5");

                    b.HasIndex(new[] { "IdListRoom" }, "IX_Room_IdListRoom");

                    b.HasIndex(new[] { "IdOwner" }, "IX_Room_IdOwner");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("API_Server.src.Models.RoomImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__RoomImag__3214EC07E1465E24");

                    b.HasIndex(new[] { "IdRoom" }, "IX_RoomImage_IdRoom");

                    b.ToTable("RoomImage", (string)null);
                });

            modelBuilder.Entity("API_Server.src.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PricePerUnit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Service__3214EC0786630AD1");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("API_Server.src.Models.Bill", b =>
                {
                    b.HasOne("API_Server.src.Models.Person", "IdPersonNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("IdPerson")
                        .HasConstraintName("FK__Bill__IdPerson__5DCAEF64");

                    b.HasOne("API_Server.src.Models.Room", "IdRoomNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("IdRoom")
                        .HasConstraintName("FK__Bill__IdRoom__5CD6CB2B");

                    b.Navigation("IdPersonNavigation");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("API_Server.src.Models.BillDetail", b =>
                {
                    b.HasOne("API_Server.src.Models.Bill", "IdBillNavigation")
                        .WithOne("BillDetail")
                        .HasForeignKey("API_Server.src.Models.BillDetail", "IdBill")
                        .HasConstraintName("FK__BillDetai__IdBil__619B8048");

                    b.HasOne("API_Server.src.Models.Service", "IdServiceNavigation")
                        .WithMany("BillDetails")
                        .HasForeignKey("IdService")
                        .HasConstraintName("FK__BillDetai__IdSer__628FA481");

                    b.Navigation("IdBillNavigation");

                    b.Navigation("IdServiceNavigation");
                });

            modelBuilder.Entity("API_Server.src.Models.BookingRequest", b =>
                {
                    b.HasOne("API_Server.src.Models.Person", "IdRenterNavigation")
                        .WithMany("BookingRequests")
                        .HasForeignKey("IdRenter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BookingRequest__IdRenter");

                    b.HasOne("API_Server.src.Models.Room", "IdRoomNavigation")
                        .WithMany("BookingRequests")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BookingRequest__IdRoom");

                    b.Navigation("IdRenterNavigation");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("API_Server.src.Models.Contract", b =>
                {
                    b.HasOne("API_Server.src.Models.Person", "IdRenterNavigation")
                        .WithMany("Contracts")
                        .HasForeignKey("IdRenter")
                        .HasConstraintName("FK__Contract__IdRent__59063A47");

                    b.HasOne("API_Server.src.Models.Room", "IdRoomNavigation")
                        .WithMany("Contracts")
                        .HasForeignKey("IdRoom")
                        .HasConstraintName("FK__Contract__IdRoom__5812160E");

                    b.Navigation("IdRenterNavigation");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("API_Server.src.Models.Expense", b =>
                {
                    b.HasOne("API_Server.src.Models.Person", "IdOwnerNavigation")
                        .WithMany("Expenses")
                        .HasForeignKey("IdOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Server.src.Models.Room", "IdRoomNavigation")
                        .WithMany("Expenses")
                        .HasForeignKey("IdRoom");

                    b.Navigation("IdOwnerNavigation");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("API_Server.src.Models.ListRoom", b =>
                {
                    b.HasOne("API_Server.src.Models.Person", "IdOwnerNavigation")
                        .WithMany("ListRooms")
                        .HasForeignKey("IdOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdOwnerNavigation");
                });

            modelBuilder.Entity("API_Server.src.Models.Notice", b =>
                {
                    b.HasOne("API_Server.src.Models.Report", "IdreportNavigation")
                        .WithOne("Notice")
                        .HasForeignKey("API_Server.src.Models.Notice", "Idreport")
                        .HasConstraintName("FK__Notice__IDReport__74AE54BC");

                    b.Navigation("IdreportNavigation");
                });

            modelBuilder.Entity("API_Server.src.Models.Payment", b =>
                {
                    b.HasOne("API_Server.src.Models.Bill", "IdBillNavigation")
                        .WithOne("Payment")
                        .HasForeignKey("API_Server.src.Models.Payment", "IdBill")
                        .IsRequired()
                        .HasConstraintName("FK__Payment__IdBill__778AC167");

                    b.Navigation("IdBillNavigation");
                });

            modelBuilder.Entity("API_Server.src.Models.Person", b =>
                {
                    b.HasOne("API_Server.src.Models.PersonDetail", "IdDetailNavigation")
                        .WithOne("Person")
                        .HasForeignKey("API_Server.src.Models.Person", "IdDetail")
                        .HasConstraintName("FK__Person__IdDetail__4D94879B");

                    b.Navigation("IdDetailNavigation");
                });

            modelBuilder.Entity("API_Server.src.Models.Report", b =>
                {
                    b.HasOne("API_Server.src.Models.Person", "IdReporterNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdReporter")
                        .HasConstraintName("FK__Report__IdReport__6E01572D");

                    b.HasOne("API_Server.src.Models.Room", "IdRoomNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdRoom")
                        .HasConstraintName("FK__Report__IdRoom__6EF57B66");

                    b.Navigation("IdReporterNavigation");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("API_Server.src.Models.Room", b =>
                {
                    b.HasOne("API_Server.src.Models.ListRoom", "IdListRoomNavigation")
                        .WithMany("Rooms")
                        .HasForeignKey("IdListRoom");

                    b.HasOne("API_Server.src.Models.Person", "IdOwnerNavigation")
                        .WithMany("Rooms")
                        .HasForeignKey("IdOwner")
                        .HasConstraintName("FK__Room__IdOwner__5165187F");

                    b.Navigation("IdListRoomNavigation");

                    b.Navigation("IdOwnerNavigation");
                });

            modelBuilder.Entity("API_Server.src.Models.RoomImage", b =>
                {
                    b.HasOne("API_Server.src.Models.Room", "IdRoomNavigation")
                        .WithMany("RoomImages")
                        .HasForeignKey("IdRoom")
                        .HasConstraintName("FK__RoomImage__IdRoo__6A30C649");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("API_Server.src.Models.Bill", b =>
                {
                    b.Navigation("BillDetail");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("API_Server.src.Models.ListRoom", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("API_Server.src.Models.Person", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("BookingRequests");

                    b.Navigation("Contracts");

                    b.Navigation("Expenses");

                    b.Navigation("ListRooms");

                    b.Navigation("Reports");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("API_Server.src.Models.PersonDetail", b =>
                {
                    b.Navigation("Person");
                });

            modelBuilder.Entity("API_Server.src.Models.Report", b =>
                {
                    b.Navigation("Notice");
                });

            modelBuilder.Entity("API_Server.src.Models.Room", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("BookingRequests");

                    b.Navigation("Contracts");

                    b.Navigation("Expenses");

                    b.Navigation("Reports");

                    b.Navigation("RoomImages");
                });

            modelBuilder.Entity("API_Server.src.Models.Service", b =>
                {
                    b.Navigation("BillDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
