// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyPhongTro.src.Models;

#nullable disable

namespace QuanLyPhongTro.Migrations
{
    [DbContext(typeof(AppContextDB))]
    partial class AppContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("IdPerson")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalMoney")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Bill__3214EC07971BEEA9");

                    b.HasIndex("IdPerson");

                    b.HasIndex("IdRoom");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.BillDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("Electricity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("IdBill")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdService")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Water")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .HasName("PK__BillDeta__3214EC073E2B9BA4");

                    b.HasIndex("IdBill")
                        .IsUnique()
                        .HasFilter("[IdBill] IS NOT NULL");

                    b.HasIndex("IdService");

                    b.ToTable("BillDetail");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.BookingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DesiredDurationMonths")
                        .HasColumnType("int");

                    b.Property<DateTime>("DesiredStartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdRenter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdRenter");

                    b.HasIndex("IdRoom");

                    b.ToTable("BookingRequests");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("IdRenter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Contract__3214EC07A2341402");

                    b.HasIndex("IdRenter");

                    b.HasIndex("IdRoom");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateIncurred")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdOwner");

                    b.HasIndex("IdRoom");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.ListRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdOwner");

                    b.ToTable("ListRoom");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Notice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Idreport")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDReport");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Notice__3214EC071255475A");

                    b.HasIndex("Idreport")
                        .IsUnique()
                        .HasFilter("[IDReport] IS NOT NULL");

                    b.ToTable("Notice");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Payment", b =>
                {
                    b.Property<Guid>("IdBill")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdBill")
                        .HasName("PK__Payment__24A2D64DE1749AF2");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("IdDetail")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Person__3214EC07FDB564BD");

                    b.HasIndex("IdDetail")
                        .IsUnique()
                        .HasFilter("[IdDetail] IS NOT NULL");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.PersonDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<byte[]>("CccdImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Gmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__PersonDe__3214EC074CE93A01");

                    b.ToTable("PersonDetail");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdReporter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Report__3214EC073003D7A2");

                    b.HasIndex("IdReporter");

                    b.HasIndex("IdRoom");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("IdListRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Room__3214EC0720EB1BA5");

                    b.HasIndex("IdListRoom");

                    b.HasIndex("IdOwner");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.RoomImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__RoomImag__3214EC07E1465E24");

                    b.HasIndex("IdRoom");

                    b.ToTable("RoomImage");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PricePerUnit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Service__3214EC0786630AD1");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Bill", b =>
                {
                    b.HasOne("QuanLyPhongTro.src.Models.Person", "IdPersonNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("IdPerson")
                        .HasConstraintName("FK__Bill__IdPerson__5DCAEF64");

                    b.HasOne("QuanLyPhongTro.src.Models.Room", "IdRoomNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("IdRoom")
                        .HasConstraintName("FK__Bill__IdRoom__5CD6CB2B");

                    b.Navigation("IdPersonNavigation");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.BillDetail", b =>
                {
                    b.HasOne("QuanLyPhongTro.src.Models.Bill", "IdBillNavigation")
                        .WithOne("BillDetails")
                        .HasForeignKey("QuanLyPhongTro.src.Models.BillDetail", "IdBill")
                        .HasConstraintName("FK__BillDetai__IdBil__619B8048");

                    b.HasOne("QuanLyPhongTro.src.Models.Service", "IdServiceNavigation")
                        .WithMany("BillDetails")
                        .HasForeignKey("IdService")
                        .HasConstraintName("FK__BillDetai__IdSer__628FA481");

                    b.Navigation("IdBillNavigation");

                    b.Navigation("IdServiceNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.BookingRequest", b =>
                {
                    b.HasOne("QuanLyPhongTro.src.Models.Person", "Renter")
                        .WithMany()
                        .HasForeignKey("IdRenter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyPhongTro.src.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Renter");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Contract", b =>
                {
                    b.HasOne("QuanLyPhongTro.src.Models.Person", "IdRenterNavigation")
                        .WithMany("Contracts")
                        .HasForeignKey("IdRenter")
                        .HasConstraintName("FK__Contract__IdRent__59063A47");

                    b.HasOne("QuanLyPhongTro.src.Models.Room", "IdRoomNavigation")
                        .WithMany("Contracts")
                        .HasForeignKey("IdRoom")
                        .HasConstraintName("FK__Contract__IdRoom__5812160E");

                    b.Navigation("IdRenterNavigation");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Expense", b =>
                {
                    b.HasOne("QuanLyPhongTro.src.Models.Person", "Owner")
                        .WithMany()
                        .HasForeignKey("IdOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyPhongTro.src.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("IdRoom");

                    b.Navigation("Owner");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.ListRoom", b =>
                {
                    b.HasOne("QuanLyPhongTro.src.Models.Person", "Owner")
                        .WithMany()
                        .HasForeignKey("IdOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Notice", b =>
                {
                    b.HasOne("QuanLyPhongTro.src.Models.Report", "IdreportNavigation")
                        .WithOne("Notice")
                        .HasForeignKey("QuanLyPhongTro.src.Models.Notice", "Idreport")
                        .HasConstraintName("FK__Notice__IDReport__74AE54BC");

                    b.Navigation("IdreportNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Payment", b =>
                {
                    b.HasOne("QuanLyPhongTro.src.Models.Bill", "IdPaymentNavigation")
                        .WithOne("Payment")
                        .HasForeignKey("QuanLyPhongTro.src.Models.Payment", "IdBill")
                        .IsRequired()
                        .HasConstraintName("FK__Payment__IdBill__778AC167");

                    b.Navigation("IdPaymentNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Person", b =>
                {
                    b.HasOne("QuanLyPhongTro.src.Models.PersonDetail", "IdDetailNavigation")
                        .WithOne("People")
                        .HasForeignKey("QuanLyPhongTro.src.Models.Person", "IdDetail")
                        .HasConstraintName("FK__Person__IdDetail__4D94879B");

                    b.Navigation("IdDetailNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Report", b =>
                {
                    b.HasOne("QuanLyPhongTro.src.Models.Person", "IdReporterNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdReporter")
                        .HasConstraintName("FK__Report__IdReport__6E01572D");

                    b.HasOne("QuanLyPhongTro.src.Models.Room", "IdRoomNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdRoom")
                        .HasConstraintName("FK__Report__IdRoom__6EF57B66");

                    b.Navigation("IdReporterNavigation");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Room", b =>
                {
                    b.HasOne("QuanLyPhongTro.src.Models.ListRoom", "ListRooms")
                        .WithMany("Rooms")
                        .HasForeignKey("IdListRoom");

                    b.HasOne("QuanLyPhongTro.src.Models.Person", "IdOwnerNavigation")
                        .WithMany("Rooms")
                        .HasForeignKey("IdOwner")
                        .HasConstraintName("FK__Room__IdOwner__5165187F");

                    b.Navigation("IdOwnerNavigation");

                    b.Navigation("ListRooms");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.RoomImage", b =>
                {
                    b.HasOne("QuanLyPhongTro.src.Models.Room", "IdRoomNavigation")
                        .WithMany("RoomImages")
                        .HasForeignKey("IdRoom")
                        .HasConstraintName("FK__RoomImage__IdRoo__6A30C649");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Bill", b =>
                {
                    b.Navigation("BillDetails")
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.ListRoom", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Person", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Contracts");

                    b.Navigation("Reports");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.PersonDetail", b =>
                {
                    b.Navigation("People")
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Report", b =>
                {
                    b.Navigation("Notice");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Room", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Contracts");

                    b.Navigation("Reports");

                    b.Navigation("RoomImages");
                });

            modelBuilder.Entity("QuanLyPhongTro.src.Models.Service", b =>
                {
                    b.Navigation("BillDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
