// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyPhongTro.Data;

#nullable disable

namespace QuanLyPhongTro.Migrations
{
    [DbContext(typeof(AppContextDB))]
    [Migration("20251108183117_AddRoomImagesRelation")]
    partial class AddRoomImagesRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyPhongTro.Model.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPerson")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalMoney")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdPerson");

                    b.HasIndex("IdRoom");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.BillDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdBill")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdService")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdBill");

                    b.HasIndex("IdService");

                    b.ToTable("BillDetails");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdRenter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdRenter");

                    b.HasIndex("IdRoom");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("IdBill")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdBill");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDetail")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdDetail")
                        .IsUnique()
                        .HasFilter("[IdDetail] IS NOT NULL");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.PersonDetailcs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Avatar")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("PersonDetails");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdReporter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdReporter");

                    b.HasIndex("IdRoom");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("IdOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdOwner");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.RoomImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdRoom");

                    b.ToTable("RoomImages");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Bill", b =>
                {
                    b.HasOne("QuanLyPhongTro.Model.Person", "Person")
                        .WithMany()
                        .HasForeignKey("IdPerson");

                    b.HasOne("QuanLyPhongTro.Model.Room", "Room")
                        .WithMany()
                        .HasForeignKey("IdRoom");

                    b.Navigation("Person");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.BillDetail", b =>
                {
                    b.HasOne("QuanLyPhongTro.Model.Bill", "Bill")
                        .WithMany("BillDetails")
                        .HasForeignKey("IdBill");

                    b.HasOne("QuanLyPhongTro.Model.Service", "Service")
                        .WithMany("BillDetails")
                        .HasForeignKey("IdService");

                    b.Navigation("Bill");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Contract", b =>
                {
                    b.HasOne("QuanLyPhongTro.Model.Person", "Renter")
                        .WithMany()
                        .HasForeignKey("IdRenter");

                    b.HasOne("QuanLyPhongTro.Model.Room", "Room")
                        .WithMany()
                        .HasForeignKey("IdRoom");

                    b.Navigation("Renter");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Payment", b =>
                {
                    b.HasOne("QuanLyPhongTro.Model.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("IdBill");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Person", b =>
                {
                    b.HasOne("QuanLyPhongTro.Model.PersonDetailcs", "PersonDetail")
                        .WithOne("Person")
                        .HasForeignKey("QuanLyPhongTro.Model.Person", "IdDetail");

                    b.Navigation("PersonDetail");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Report", b =>
                {
                    b.HasOne("QuanLyPhongTro.Model.Person", "Reporter")
                        .WithMany()
                        .HasForeignKey("IdReporter");

                    b.HasOne("QuanLyPhongTro.Model.Room", "Room")
                        .WithMany()
                        .HasForeignKey("IdRoom");

                    b.Navigation("Reporter");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Room", b =>
                {
                    b.HasOne("QuanLyPhongTro.Model.Person", "Owner")
                        .WithMany()
                        .HasForeignKey("IdOwner");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.RoomImage", b =>
                {
                    b.HasOne("QuanLyPhongTro.Model.Room", "Room")
                        .WithMany("RoomImages")
                        .HasForeignKey("IdRoom");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Bill", b =>
                {
                    b.Navigation("BillDetails");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.PersonDetailcs", b =>
                {
                    b.Navigation("Person")
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Room", b =>
                {
                    b.Navigation("RoomImages");
                });

            modelBuilder.Entity("QuanLyPhongTro.Model.Service", b =>
                {
                    b.Navigation("BillDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
